version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - DOCS_VERSION=${DOCS_VERSION}
      - HOST=${HOST}
      - BASE_PATH=${BASE_PATH}
